class ContinueError(Exception):
    pass


class BreakError(Exception):
    pass
